routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::view('sobre','about');

Route::resource('/contatos', 'ContatosController');

Route::resource('/telefones', 'TelefonesController');

app/Contato.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Contato extends Model
{
    use Notifiable;

    protected $fillable = [];

    protected $hidden = [];

    protected $guarded = [];

    public function telefones(){

        return $this->hasMany('App\Telefone');
    }
}

app/Telefone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Telefone extends Model
{
    use Notifiable;

    protected $fillable = [];

    protected $hidden = [];

    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContatosController.php
<?php

namespace App\Http\Controllers;

use App\Contato;
use App\Telefone;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class ContatosController extends Controller
{

    public function saveDateTime($data)
    {
        if ($data != '') {
            return implode("-", array_reverse(explode("/", $data)));
        } else {
            return '0000-00-00';
        }
    }

    public function getCep($cep)
    {
        $cep = str_replace('.', '', $cep);
        $cep = str_replace('-', '', $cep);
        $reg = simplexml_load_file("http://cep.republicavirtual.com.br/web_cep.php?formato=txt&cep=" . $cep);
        $dados['success'] = (string)$reg->resultado;
        $endereco = (string)$reg->tipo_logradouro . ' ' . $reg->logradouro.',  '.(string)$reg->bairro.' '.(string)$reg->cidade.'-'.(string)$reg->uf;
        return $endereco;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('contatos.index')->with('contatos', Contato::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('contatos.create');
    }

    /**
     * salvar.
    */

    public function store(Request $request)
    {
        $data = $request->all();

        $data['data_nasc'] = $this->saveDateTime($data['data_nasc']);

        $validator = Validator::make($data,[
            'nome' => 'required|max:100',
            'sobrenome' => 'required|max:100',
            'data_nasc' => 'required|date',
            'email' => 'required|max:255|unique:contatos'
        ]);

        if ($validator->fails()) {
            return redirect()->route('contatos.create')
                ->withErrors($validator)
                ->withInput();
        }

        Contato::create($data);
        $request->session()->flash('success', 'Registro adicionado com sucesso!');
        return redirect()->route('contatos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       return view('contatos.edit')->with(['contato' => Contato::findOrFail($id), 'telefones' => Telefone::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, $id)
    {
        $contato = Contato::findOrFail($id);

        $data = $request->all();

        $data['data_nasc'] = $this->saveDateTime($data['data_nasc']);

        $validator = Validator::make($data,[
            'nome' => 'required|max:100',
            'sobrenome' => 'required|max:100',
            'data_nasc' => 'required|date',
            'email' => [
                'required',
                Rule::unique('users')->ignore($contato->id),
            ]
        ]);

        if ($validator->fails()) {
            return redirect()->route('contatos.create')
                ->withErrors($validator)
                ->withInput();
        }

        $contato->fill($data)->save();
        $request->session()->flash('success', 'Registro atualizado com sucesso!');
        return redirect()->route('contatos.index');
    }

    /**
     * Remove the specified resource from storage.
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy(Request $request,$id)
    {
        $contato = Contato::find($id);
        $contato->delete();
        $request->session()->flash('success', 'Contato excluído com sucesso!');
        return redirect()->back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TelefonesController.php
<?php

namespace App\Http\Controllers;

use App\Telefone;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use mysql_xdevapi\Session;

class TelefonesController extends Controller
{

    public function store(Request $request)
    {
        $data = $request->all();

        $validator = Validator::make($data,[
            'numero' => 'required|max:100',
            'endereco' => 'required|max:400',
            'cep' => 'required|max:10',
        ]);

        if ($validator->fails()) {
            return redirect()->route('contatos.edit',$data['contato_id'])
                ->withErrors($validator)
                ->withInput();
        }

        Telefone::create($data);
        $request->session()->flash('success', 'Registro adicionado com sucesso!');
        return redirect()->back();
    }


    public function destroy(Request $request,$id)
    {
        $telefone = Telefone::find($id);
        $telefone->delete();
        $request->session()->flash('success', 'Registro excluído com sucesso!');
        return redirect()->back();
    }
}

resources/views/about.blade.php
@extends('layout.default')

@section('content')
    <div class="col-md-8 col-lg-12 order-md-1">
        <h4 class="mb-3">Desenvolvedor</h4>
        <hr class="mb-4">
        <div class="d-flex">
            <div class="col-md-12 mb-12">
                <h3>Rogério Gomes Lopes</h3>
                <h4>(11) 97070-8735</h4>
                <p>Rua Bento Freitas 162, Ap 511 República São Paulo - SP</p>
            </div>
        </div>
    </div>
@endsection

resources/views/contatos/create.blade.php
@extends('layout.default')

@section('content')
    <div class="col-md-8 col-lg-12 order-md-1">
        <h4 class="mb-3">Novo cadastro</h4>
        <hr class="mb-4">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br />
        @endif

        <form method="post" action="{{ route('contatos.store') }}">

            @csrf

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="firstName">Nome</label>
                    <input type="text" class="form-control" name="nome" placeholder="" value="" required>
                    <div class="invalid-feedback">
                        Informe o seu primeiro nome.
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="lastName">Sobrenome</label>
                    <input type="text" class="form-control" name="sobrenome" placeholder="" value="" required>
                    <div class="invalid-feedback">
                        Informe o seu sobrenome
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control" name="email" placeholder="usuario@dominio.com">
                    <div class="invalid-feedback">
                        Informe um e-mail válido
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="address">Data de nascimento</label>
                    <input type="text" class="form-control" name="data_nasc" id="date_nasc" v-mask="'##/##/####'" placeholder="00/00/0000" required>
                    <div class="invalid-feedback">
                        Informe a sua data de nascimento.
                    </div>
                </div>
            </div>

            <span class="mb-4">

            <button class="btn btn-primary" type="submit">Salvar</button>
        </form>
    </div>
@endsection

resources/views/contatos/edit.blade.php
@extends('layout.default')

@section('content')
    <div class="col-md-8 col-lg-12 order-md-1">

        <h4 class="mb-3">Novo cadastro</h4>

        <hr class="mb-4">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif

        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
            </div>
        @endif

        <form class="needs-validation" novalidate="" action="{{ route('contatos.update', $contato->id) }}"
              method="POST">

            {{ method_field('PUT') }}

            @csrf

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="firstName">Nome</label>
                    <input type="text" class="form-control" placeholder="" name="nome" value="{{$contato->nome}}"
                           required>
                    <div class="invalid-feedback">
                        Informe o seu primeiro nome.
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="lastName">Sobrenome</label>
                    <input type="text" class="form-control" placeholder="" name="sobrenome"
                           value="{{$contato->sobrenome}}" required>
                    <div class="invalid-feedback">
                        Informe o seu sobrenome
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control" name="email" value="{{$contato->email}}"
                           placeholder="usuario@dominio.com" required>
                    <div class="invalid-feedback">
                        Informe um e-mail válido
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="address">Data de nascimento</label>
                    <input type="text" class="form-control" name="data_nasc" id="data_nasc"
                           value="{{$contato->data_nasc}}" placeholder="00/00/0000" required>
                    <div class="invalid-feedback">
                        Informe a sua data de nascimento.
                    </div>
                </div>
            </div>

            <span class="mb-4"></span>

            <button class="btn btn-primary pull-right" type="submit">Atualizar</button>

        </form>

        <h4>Telefomes / Endereços</h4>

        @if (count($contato->telefones ) <= 5)

         <hr class="mb-4">

        <form class="needs-validation" novalidate="" action="{{ route('telefones.store') }}" method="POST">
            @csrf
            <div class="row">

                <div class="col-md-2 mb-1">
                    <label for="cep">CEP</label>
                    <input type="text" class="form-control" placeholder="00000-00" v-model="cep" v-mask="'#####-###'"  id="cep" name="cep" value="" required>
                </div>

                <div class="col-md-7 mb-4">
                    <label for="endereco">Endereço</label>
                    <input type="text" class="form-control" placeholder="" id="endereco" v-model="endereco" name="endereco" value="" required>
                </div>

                <div class="col-md-3 mb-2">
                    <label for="telefone">Telefone</label>
                    <input type="text" class="form-control" placeholder="(00) 0000-0000" id="date_nasc" v-mask="'(##) ####-####'" name="numero" value="" required>
                </div>

                <input name="contato_id" type="hidden" value="{{$contato->id}}">
            </div>
            <span class="mb-4"></span>
            <button class="btn btn-primary pull-right" type="submit">Adicionar</button>
        </form>
        <br/>
        <br/>
        @endif

        <hr class="mb-4">

        <div class="row">
            <div class="col-md-12 mb-12">
                <table class="table table-striped table-borderless">
                    <thead>
                    <tr>
                        <th width="170">Telefone</th>
                        <th>Endereço</th>
                        <th  width="170">CEP</th>
                        <th width="10">Excluir</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($contato->telefones as $telefone)
                        <tr>
                            <td>{{$telefone->numero}}</td>
                            <td>{{$telefone->endereco}}</td>
                            <td>{{$telefone->cep}}</td>
                            <td>
                                <form action="{{ route('telefones.destroy', $telefone->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn" type="submit">
                                        <i style="color: red" class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>

    </div>
@endsection

resources/views/contatos/index.blade.php
@extends('layout.default')

@section('content')
    <div class="col-md-12 col-lg-12">

        <h4 class="mb-3">Cadastros</h4>

        <hr class="mb-4">

        <div class="col-md-12 mb-12 -align-right">
            <a href="{{ route('contatos.create') }}">
                <button type="button" class="btn btn-outline-dark">Novo cadastro</button>
            </a>
        </div>

        <br/>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif

        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
            </div>
        @endif


        <div class="d-flex">
            <div class="col-md-12 mb-12">
                @if (Session::has('message'))
                    <div class="alert alert-success">{{ Session::get('message') }}</div>
                @endif
            </div>
        </div>

        <br/>

        <div class="d-flex">
            <div class="col-md-12 mb-12">

                <div class="table-responsive">
                    <table class="table table-striped table-borderless">
                        <thead>
                        <tr>
                            <th>Código</th>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th>Data de nascimento</th>
                            <th>Telefones</th>
                            <th>Editar</th>
                            <th>Excluir</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($contatos as $contato)
                            <tr>
                                <td>{{$contato->id}}</td>
                                <td>{{$contato->nome}} {{$contato->sobrenome}}</td>
                                <td>{{$contato->email}}</td>
                                <td>{{$contato->data_nasc}}</td>
                                <td>
                                    @foreach($contato->telefones as $telefone)
                                    <p>{{$telefone->numero}}</p>
                                   @endforeach
                                </td>
                                <td>
                                    <a href="{{ route('contatos.edit', $contato->id) }}">
                                        <button class="btn">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <form action="{{ route('contatos.destroy', $contato->id) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn" type="submit">
                                            <i style="color: red" class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/includes/navbar.blade.php
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">API Laravel</a>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="/"></a>
        </li>
    </ul>
</nav>

resources/views/includes/sidebar.blade.php
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{{route('contatos.index')}}">
                    <span data-feather="file"></span>
                    Cadastros
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{route('contatos.create')}}">
                    <span data-feather="shopping-cart"></span>
                    Novo cadastro
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/sobre">
                    <span data-feather="users"></span>
                    Desenvolvedor
                </a>
            </li>
        </ul>
    </div>
</nav>

resources/views/layout/default.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="/css/app.css">
    <title>API - Pardini</title>
</head>
<body>
@include('includes.navbar')
<div class="container-fluid" id="app">
    <div class="row">
        @include('includes.sidebar')

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-3 m-2">
            @yield('content')
        </main>
    </div>
</div>
<script type="text/javascript" src="/js/app.js"></script>
</body>
</html>